name: Github env

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: GITHUB_REF
        run: |
          echo $GITHUB_REF
          echo ${{github.ref}}

      - name: GITHUB_EVENT_NAME
        run: |
          echo $GITHUB_EVENT_NAME
          echo ${{github.event_name}}

      - name: GITHUB_EVENT_PATH
        run: |
          echo $GITHUB_EVENT_PATH
          echo ${{github.event_path}}

      - name: GITHUB_ACTOR
        run: |
          echo $GITHUB_ACTOR
          echo ${{github.actor}}
      
      # for custom and composite action only
      # display nothing in this workflow action
      - name: GITHUB_ACTION_PATH
        run: |
          echo $GITHUB_ACTION_PATH
          echo ${{github.action_path}}
