name: Reusable Workflow Caller

on:
  push:

jobs:
  call_reusable:
    # uses: ./.github/workflows/reusable-called.yaml
    uses: aj3sh/github-actions/.github/workflows/reusable-called.yaml@main
    with:
      name: 'Ajesh Sen Thapa'

  run:
    needs: call_reusable
    runs-on: aj3sh-hosted

    steps:
      - name: Check call_reusable output
        run: echo ${{ needs.call_reusable.outputs.status }}
