name: Composite Custom Action

branding:
  color: green
  icon: shield

inputs:
  name:
    type: string
    required: true

outputs:
  status:
    description: 'Status'
    value: ${{ steps.status_out.outputs.status }}

runs:
  using: composite
  steps:
    - run: echo $NAME | cut -c 3-20
      env:
        NAME: ${{ inputs.name }}
      shell: bash
