name: Job container

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: node:20
      env:
        NAME: Ajesh
    steps:
      - run: node --version  
      - run: echo $NAME