name: Strategy

on:
  push:

jobs:
    run:
      name: '${{ matrix.color }}-${{ matrix.version }}'
      runs-on: ubuntu-latest
      strategy:
        fail-fast: true
        max-parallel: 2
        matrix:
          color: [green, blue]
          version: [1, 2, 3]

      steps:
        - uses: actions/checkout@v4
        - run: echo "Color ${{ matrix.color }}, Version ${{ matrix.version }}"
